# ---------- Theme ----------

general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# ---------- Window ----------

[window]
padding = {x = 5, y = 5}

# ---------- Font Settings ----------

[font]
size = 11.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style  = "Regular"

# ---------- Mouse & Environment ----------

[mouse]
hide_when_typing = true
